### PR TITLE
Handle evals

### LINKED ISSUE #10: After upgrade to 0.5.0: minitest fails with "uninitialized constant ActiveRecord::QueryMethods::Relation"
After upgrading from 0.4.1 to 0.5.0, some integration tests have started to break. Any pointers?

Example test:

```ruby
require "test_helper"

class ProductsControllerTest < ActionDispatch::IntegrationTest
  test "should get show" do 
    product = products(:one) # <<< this is line 5, working with a fixture
    get product_url(product)
    assert_response :success
  end
end
```

Fails with:

```
Minitest::UnexpectedError: RuntimeError: Neutered Exception NameError: uninitialized constant ActiveRecord::QueryMethods::Relation
    test/controllers/products_controller_test.rb:5:in 'block in <class:ProductsControllerTest>'
test/controllers/products_controller_test.rb:5:in 'block in <class:ProductsControllerTest>'
```

When I replace:

```ruby
product = products(:one) # <<< this is line 5, working with a fixture
get product_url(product)
assert_response :success
```

with

```ruby
    get product_url("foobar") # <<< still fails here
    assert_response :success
```

then the test fails with:

```
Minitest::UnexpectedError: RuntimeError: Neutered Exception NameError: uninitialized constant StrictIvars::KernelEvalPatch::ErrorPage
    test/controllers/products_controller_test.rb:4:in 'block in <class:ProductsControllerTest>'
test/controllers/products_controller_test.rb:4:in 'block in <class:ProductsControllerTest>'
```

## Environment

- Rails 8.0.2
- Ruby 3.4.3
- strict_ivars 0.5.0

```ruby
# config/boot.rb
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup" # Set up gems listed in the Gemfile.
require "bootsnap/setup" # Speed up boot time by caching expensive operations.

require "strict_ivars"
StrictIvars.init(include: ["#{Dir.pwd}/**/*"], exclude: ["#{Dir.pwd}/vendor/**/*"])
```

### PR DESCRIPTION
**Pull request by joeldrapper**
Unfortunately you cannot override `class_eval`, `module_eval`, etc. and call `super`. If you do, the context is wrong when `class_eval` is given a block.

This new approach instead pre-processes the arguments to `class_eval` and friends before they are called.

Closes #10

### CODE REVIEW

File: lib/strict_ivars.rb [hunk 1]
```diff
@@ -3,25 +3,71 @@
...
-		CONFIG.include(*include)
-		CONFIG.exclude(*exclude)
+	def self.init(include: EMPTY_ARRAY, exclude: EMPTY_ARRAY)
+		CONFIG.include(*include) unless include.length == 0
+		CONFIG.exclude(*exclude) unless exclude.length == 0
 
 		RequireHooks.source_transform(
-			patterns: include,
-			exclude_patterns: exclude
+			patterns: EVERYTHING,
```
Comment (joeldrapper) [inline lib/strict_ivars.rb:25]: We have to pro-process everything in order to catch evals.

File: lib/strict_ivars.rb [hunk 2]
```diff
@@ -3,25 +3,71 @@
...
+			exclude_patterns: EMPTY_ARRAY
 		) do |path, source|
 			source ||= File.read(path)
-			Processor.call(source)
+
+			if CONFIG.match?(path)
+				Processor.call(source)
```
Comment (joeldrapper) [inline lib/strict_ivars.rb:31]: We only use the main processor if the source matches the configured paths.

File: lib/strict_ivars.rb [hunk 3]
```diff
@@ -3,25 +3,71 @@
...
+			else
+				BaseProcessor.call(source)
```
Comment (joeldrapper) [inline lib/strict_ivars.rb:33]: The base processor only pre-processes eval args.

File: lib/strict_ivars.rb [hunk 4]
```diff
@@ -3,25 +3,71 @@
...
+			end
 		end
 	end
+
+	def self.process_eval_args(receiver, method_name, *args)
```
Comment (joeldrapper) [inline lib/strict_ivars.rb:38]: This method takes eval args and pre-processes them.

File: lib/strict_ivars.rb [hunk 5]
```diff
@@ -3,25 +3,71 @@
...
+		when :eval
+			if Kernel == owner
+				source, binding, file = args
+			elsif Binding == owner
+				source, file = args
+			end
+		end
+
+		if String === source
+			file ||= caller_locations(1, 1).first&.path
```
Comment (joeldrapper) [inline lib/strict_ivars.rb:62]: If no file path is given, we assume it’s the caller location path.

File: lib/strict_ivars.rb [hunk 6]
```diff
@@ -3,25 +3,71 @@
...
+
+			if CONFIG.match?(file)
+				args[0] = Processor.call(source)
+			else
+				args[0] = BaseProcessor.call(source)
+			end
```
Comment (joeldrapper) [inline lib/strict_ivars.rb:68]: Same as before, we want to continue pre-processing just the eval args if the file path isn’t an included path.

File: lib/strict_ivars/base_processor.rb [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+	attr_reader :annotations
+
+	def visit_call_node(node)
+		name = node.name
+
+		if EVAL_METHODS.include?(name) && (arguments = node.arguments)
+			location = arguments.location
+
+			if node.receiver
+				receiver_local = "__eval_receiver_#{SecureRandom.hex(8)}__"
```
Comment (joeldrapper) [inline lib/strict_ivars/base_processor.rb:38]: We need to store the specific receiver with a unique name so we can identify it later. This enables us to check if the receiver of this argument has had the eval method overridden.

**Comment by joeldrapper** [comment]
With this change, it also works in ERB.
